catering/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
]

homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('qna/', views.qna, name='qna'),
    path('about-us/', views.about_us, name='about-us'),
    path('our-team/', views.our_team, name='our-team'),
    # dilanjutkan ...
]

homepage/models.py
from django.db import models

# Create your models here.
class Answer(models.Model):
    key = models.CharField(max_length=50)
    answer = models.CharField(max_length=200)

    def __str__(self):
        return self.key

homepage/views.py
from django.shortcuts import render
from .models import Answer

# Create your views here.
def homepage(request):
    return render(request, 'Homepage.html')

def about_us(request):
    return render(request, 'About Us.html')

def our_team(request):
    return render(request, 'OurTeam-page.html')

def qna(request):
    if request.method == 'POST':
        splitted_keyword = request.POST.get('keyword').split(" ")
        answer = Answer.objects.all().get(key="notfound")
        for word in splitted_keyword:
            if len(Answer.objects.filter(key=word.lower()))==1:
                answer = Answer.objects.all().get(key=word)
        return render(request, 'QnA-page.html', {'answer' : answer})
    else:
        return render(request, 'QnA-page.html')

homepage/templates/About Us.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{%static 'css/About-style.css' %}">

    <link href="https://fonts.googleapis.com/css?family=Playfair+Display|Poppins|Roboto&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</head>
<body>
    <div id="wrapper">
        <div class="container-fluid m-auto">
                <div class="row pt-5 pl-5 pr-5">
                    <div class="col-lg-6 col-md-12 px-0 text-left content-about-us">
                        <h1>What are We?</h1>
                        <p>test test test test test test test test</p>
                        <p>test test test test test test test test</p>
                        <p></p>
                    </div>
                    <div class="col-lg-6 col-md-12 px-0 text-center content-our-team">
                        <img src="{% static 'images/undraw_healthy_options_sdo3.svg' %}" alt="Application" class="about-us-img" />
                    </div>
                </div>

                <div class="row pt-5 pl-5 pr-5">
                    <div class="col-lg-6 col-md-12 px-0 text-center content-our-team">
                        <img src="{% static 'images/Artboard 1.png' %}" alt="Application" class="about-us-img" />
                    </div>
                    <div class="col-lg-6 col-md-12 px-0 text-right content-about-us">
                        <h1>What are We Serving?</h1>
                        <p></p>
                    </div>
                </div>

                <div class="row pt-5 pl-5 pr-5">
                    <div class="col-lg-6 col-md-12 px-0 text-left content-about-us">
                        <h1>What are We?</h1>
                        <p></p>
                    </div>
                    <div class="col-lg-6 col-md-12 px-0 text-justify content-our-team">

                    </div>
                </div>

        </div>
    </div>
    <div class="d-flex flex-row-reverse bd-highlight justify-content-center">
        <div class="p-2 bd-highlight text-center">Back to Menu >>></div>
        <div class="p-2 bd-highlight text-center"><a href="{% url 'homepage:our-team' %}">Our Team</a></div>
        <div class="p-2 bd-highlight text-center">About Us</div>
        
    </div>
</body>
</html>

homepage/templates/Homepage.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Cater-ing | ...</title>

    <link rel="stylesheet" href="{% static 'css/Homepage-style.css' %}">

    <link href="https://fonts.googleapis.com/css?family=Playfair+Display|Poppins|Roboto&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

</head>
<body>
    <div class="row">
        <div class="col-6"></div>
        <div class="col-6">
            <div class="container text-right">
                <h1>Welcome!</h1>
                <p> We provide delicious healthy food <br>
                    and send it to your doorstep!</p>
                <a href="{% url 'homepage:qna' %}"><button type="submit" class="btn btn-info">Explore</button></a>
                <a href="{% url 'homepage:about-us' %}"><button type="submit" class="btn btn-info">About Us</button></a>
            </div>
        </div>
    </div>
</body>
</html>

homepage/templates/OurTeam-page.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>

    <link rel="stylesheet" href="{%static 'css/OurTeam-style.css' %}">

    <link href="https://fonts.googleapis.com/css?family=Playfair+Display|Poppins|Roboto&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

</head>
<body>
    <div id="wrapper">
        <div class="container m-auto ">
            <div class="leftmost rightmost">
                <div class="row mx-2 h-100">
                    <div class="col-lg-6 col-md-12 px-2 my-auto text-justify content-our-team">
                        <h1 class="our-team-title">Our Team</h1>
                        <p class="our-team-subtitle"> We are from group 12, consisted of Alia, Ferdinand, Mikhael, and Jilham.
                            this is our first project in creating a website to fulfill the first group 
                            assignments in the course of web desing and programming. 

                        </p>
                    </div>
                    <div class="col-lg-6 col-md-12 px-2 text-center">
                        <img src="{% static 'images/undraw_team_spirit_hrr4.svg' %}" alt="Out Team Design" class="our-team-img">
                    </div>
                </div>
        
                <h3 class="text-center mt-5 our-team-text">~ Let's meet our fabulous creator ~</h3>
                <div id="carouselExampleControls" class="carousel slide carousel-background" data-ride="carousel">
                    <div class="carousel-inner">
                        <div class="carousel-item active">
                            <div class="carousel-content">
                                <img src="{% static 'images/Jilham Luthfi.jpg' %}" class="mx-auto d-block carousel-img" alt="Jilham Luthfi">
                                <div class="carousel-subtitle">
                                    <h5><strong>M. Jilham Luthfi</strong></h5>
                                    <p>Contribute in making of Q&A and About Us pages</p>
                                </div>
                            </div>
                        </div>
                        <div class="carousel-item">
                            <div class="carousel-content">
                                <img src="{% static 'images/Alia.png' %}" class="mx-auto d-block carousel-img" alt="Alia Junisar">
                                <div class="carousel-subtitle white-text">
                                    <h5><strong>Alia Junisar</strong></h5>
                                    <p>-</p>
                                </div>
                            </div>
                        </div>
                        <div class="carousel-item">
                            <div class="carousel-content">
                                <img src="{% static 'images/Jilham Luthfi.jpg' %}" class="mx-auto d-block carousel-img" alt="Jilham Luthfi">
                                <div class="carousel-subtitle white-text">
                                    <h5><strong>M. Jilham Luthfi</strong></h5>
                                    <p>-</p>
                                </div>
                            </div>
                        </div>
                        <div class="carousel-item">
                            <div class="carousel-content">
                                <img src="{% static 'images/Jilham Luthfi.jpg' %}" class="mx-auto d-block carousel-img" alt="Jilham Luthfi">
                                <div class="carousel-subtitle white-text">
                                    <h5><strong>M. Jilham Luthfi</strong></h5>
                                    <p>-</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
            </div>
        </div>
    </div>
    <div class="d-flex flex-row-reverse bd-highlight justify-content-center">
        <div class="p-2 bd-highlight text-center">Back to Menu >>></div>
        <div class="p-2 bd-highlight text-center">Our Team</div>
        <div class="p-2 bd-highlight text-center"><a href="{% url 'homepage:about-us' %}">About Us</a></div>
    </div>
    
    
</body>
</html>

homepage/templates/QnA-page.html
{% extends 'base.html' %}
{% block content %}
    <div class="container mt-5 pt-5">
        <div class="row justify-content-center p-5">
            <form class="text-center" method="POST">
                {% csrf_token %}
                <h1>Feel free to ask</h1>
                <input class="form-control input-style center-content" type="text" name="keyword" placeholder="Type something">
                <button type="submit" class="btn btn-primary">Search</button>
            </form>
            
            <div class="mt-3 answer-box">
                {{answer.answer}}
            </div>
        </div>
    </div>
{% endblock %}

homepage/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>QnA | Cater.ing</title>

    <link rel="stylesheet" href="{%static 'css/Navbar-style.css' %}"> 
    <link rel="stylesheet" href="{%static 'css/QnA-style.css' %}">

    <link href="https://fonts.googleapis.com/css?family=Lobster&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display|Poppins|Roboto&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-info fixed-top">
        <a class="navbar-brand header-title" href="#"><img src="{% static 'images/favicon.png' %}" width="50" height="50" alt="">
            <span class="header-title">Cater.ing</span>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
                
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active header-subtitle">
                    <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active header-subtitle">
                    <a class="nav-link" href="#">Menu <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active header-subtitle">
                    <a class="nav-link" href="#">Q&A<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active header-subtitle">
                    <a class="nav-link" href="#">Article <span class="sr-only">(current)</span></a>
                </li>
            </ul>
            <a href="#" class="btn btn-warning header-subtitle">Order Now</a> 
        </div>    
    </nav>

    {% block content %}
    {% endblock %}
</body>